version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "github.com/coredns/caddy"
        update-types: ["version-update:semver-major"]
