package k8scrd

/*
Copyright 2022 The k8gb Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"os"

	restclient "k8s.io/client-go/rest"
	"k8s.io/client-go/tools/clientcmd"
)

type configType string

const (
	inClusterConfigType configType = "inCluster"
	localConfigType     configType = "local"
)

// config factory provides k8s config based on argument.
func configFactory(ct configType) (cfg *restclient.Config, rct configType, err error) {
	rct = ct
	switch ct {
	case localConfigType:
		kubeconfig := os.Getenv("KUBECONFIG")
		cfg, err = clientcmd.BuildConfigFromFlags("", kubeconfig)
	case inClusterConfigType:
		fallthrough
	default:
		cfg, err = restclient.InClusterConfig()
		rct = inClusterConfigType
	}
	return cfg, rct, err
}
