apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: coredns-wildcard
  labels:
    k8gb.absa.oss/dnstype: local
spec:
  endpoints:
  # Wildcard DNS entry - matches any single-level subdomain
  - dnsName: "*.example.org"
    recordType: A
    recordTTL: 30
    targets:
    - 192.168.1.100
    - 192.168.1.101
  # Exact match takes precedence over wildcard
  - dnsName: "specific.example.org"
    recordType: A
    recordTTL: 30
    targets:
    - 10.0.0.1
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: coredns-wildcard-multilevel
  labels:
    k8gb.absa.oss/dnstype: local
spec:
  endpoints:
  # Wildcard for deeper subdomains
  - dnsName: "*.app.example.org"
    recordType: A
    recordTTL: 30
    targets:
    - 10.20.30.40
    - 10.20.30.41
