package gateway

/*
Copyright 2022 The k8gb Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"net"
	"strings"
	"time"

	"github.com/coredns/coredns/plugin/pkg/dnsutil"
	"github.com/coredns/coredns/request"
	"github.com/k8gb-io/coredns-crd-plugin/common/k8sctrl"
	"github.com/k8gb-io/coredns-crd-plugin/common/netutils"

	"github.com/miekg/dns"
)

// serveApex serves request that hit the zone' apex. A reply is written back to the client.
func (gw *Gateway) serveApex(state request.Request) int {
	log.Infof("Serving apex for %s", state.Zone)
	m := new(dns.Msg)
	m.SetReply(state.Req)
	switch state.QType() {
	case dns.TypeSOA:
		m.Answer = []dns.RR{gw.soa(state)}

		// Adding the NS records fixes some of the picky DNS resolvers
		ns := gw.ns(state)
		rr := []dns.RR{}
		for _, n := range ns {
			rr = append(rr, n)
		}
		m.Ns = rr

	case dns.TypeNS:
		// get the NS records
		ns := gw.ns(state)
		rr := []dns.RR{}
		glueNames := []string{}
		for _, n := range ns {
			rr = append(rr, n)
			glueNames = append(glueNames, n.Ns)
		}
		m.Answer = rr

		// get the glue records
		for _, glueName := range glueNames {
			log.Infof("looking up glue records for %s", glueName)
			indexKey := netutils.StripClosingDot(glueName)
			ep := k8sctrl.Resources.DNSEndpoint.Lookup(indexKey, net.ParseIP(state.IP()), "")

			for _, target := range ep.Targets {
				log.Infof("adding glue record %s for %s", target, indexKey)
				header := dns.RR_Header{Name: glueName, Rrtype: dns.TypeA, Ttl: gw.opts.ttlHigh, Class: dns.ClassINET}
				rr := &dns.A{Hdr: header, A: net.ParseIP(target)}
				m.Extra = append(m.Extra, rr)
			}
		}
		log.Info("got glue records")
	}

	if err := state.W.WriteMsg(m); err != nil {
		log.Errorf("Failed to send a response: %s", err)
	}
	return 0
}

func (gw *Gateway) soa(state request.Request) *dns.SOA {
	header := dns.RR_Header{Name: state.Zone, Rrtype: dns.TypeSOA, Ttl: gw.opts.ttlHigh, Class: dns.ClassINET}

	soa := &dns.SOA{Hdr: header,
		Mbox:    dnsutil.Join(gw.opts.hostmaster, state.Zone),
		Ns:      dnsutil.Join(gw.opts.hostname, state.Zone),
		Serial:  uint32(time.Now().Truncate(time.Hour).Unix()),
		Refresh: 7200,
		Retry:   1800,
		Expire:  86400,
		Minttl:  gw.opts.ttlHigh,
	}
	return soa
}

func (gw *Gateway) ns(state request.Request) []*dns.NS {
	ns := []*dns.NS{}
	header := dns.RR_Header{Name: state.Zone, Rrtype: dns.TypeNS, Ttl: gw.opts.ttlHigh, Class: dns.ClassINET}

	indexKey := netutils.StripClosingDot(state.QName())
	ep := k8sctrl.Resources.DNSEndpoint.Lookup(indexKey, net.ParseIP(state.IP()), "")
	for _, target := range ep.Targets {
		if !strings.HasSuffix(target, ".") {
			target += "."
		}
		ns = append(ns, &dns.NS{Hdr: header, Ns: target})
	}

	return ns
}
