package service

/*
Copyright 2022 The k8gb Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"context"
	"fmt"
	"testing"

	"github.com/coredns/coredns/plugin"
	"github.com/golang/mock/gomock"
	dns "github.com/miekg/dns"
	"github.com/stretchr/testify/assert"
)

type fakePlugin struct {
	handler plugin.Handler
}

type fakeWriter struct {
	writer dns.ResponseWriter
}

func newFakeHandler(ctrl *gomock.Controller, f func(h *MockHandler)) fakePlugin {
	h := NewMockHandler(ctrl)
	f(h)
	return fakePlugin{
		handler: h,
	}
}

func newFakeWriter(ctrl *gomock.Controller, f func(w *MockResponseWriter)) fakeWriter {
	w := NewMockResponseWriter(ctrl)
	f(w)
	return fakeWriter{
		writer: w,
	}
}

func TestContainer(t *testing.T) {
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	tests := []struct {
		name          string
		expectedError bool
		writer        fakeWriter
		plugin        []fakePlugin
	}{
		{
			name: "OneHandlerSucceed",
			writer: newFakeWriter(ctrl, func(w *MockResponseWriter) {
				w.EXPECT().WriteMsg(gomock.Any()).Return(nil).Times(1)
			}),
			plugin: []fakePlugin{
				newFakeHandler(ctrl, func(h *MockHandler) {
					h.EXPECT().ServeDNS(gomock.Any(), gomock.Any(), gomock.Any()).Return(dns.RcodeSuccess, nil).Times(1)
				})},
		},
		{
			name: "TwoHandlersSucceed",
			writer: newFakeWriter(ctrl, func(w *MockResponseWriter) {
				w.EXPECT().WriteMsg(gomock.Any()).Return(nil).Times(1)
			}),
			plugin: []fakePlugin{
				newFakeHandler(ctrl, func(h *MockHandler) {
					h.EXPECT().ServeDNS(gomock.Any(), gomock.Any(), gomock.Any()).Return(dns.RcodeSuccess, nil).Times(1)
				}),
				newFakeHandler(ctrl, func(h *MockHandler) {
					h.EXPECT().ServeDNS(gomock.Any(), gomock.Any(), gomock.Any()).Return(dns.RcodeSuccess, nil).Times(1)
				})},
		},
		{
			name: "NoHandlers",
			writer: newFakeWriter(ctrl, func(w *MockResponseWriter) {
				w.EXPECT().WriteMsg(gomock.Any()).Return(nil).Times(1)
			}),
			plugin: []fakePlugin{},
		},
		{
			name:          "FirstHandlerError",
			expectedError: true,
			writer:        newFakeWriter(ctrl, func(w *MockResponseWriter) {}),
			plugin: []fakePlugin{
				newFakeHandler(ctrl, func(h *MockHandler) {
					h.EXPECT().Name().Return("fake").Times(1)
					h.EXPECT().ServeDNS(gomock.Any(), gomock.Any(), gomock.Any()).Return(dns.RcodeSuccess, fmt.Errorf("fake")).Times(1)
				}),
				newFakeHandler(ctrl, func(h *MockHandler) {})},
		},
		{
			name:          "SecondHandlerError",
			expectedError: true,
			writer:        newFakeWriter(ctrl, func(w *MockResponseWriter) {}),
			plugin: []fakePlugin{
				newFakeHandler(ctrl, func(h *MockHandler) {
					h.EXPECT().ServeDNS(gomock.Any(), gomock.Any(), gomock.Any()).Return(dns.RcodeSuccess, nil).Times(1)
				}),
				newFakeHandler(ctrl, func(h *MockHandler) {
					h.EXPECT().Name().Return("fake").Times(1)
					h.EXPECT().ServeDNS(gomock.Any(), gomock.Any(), gomock.Any()).Return(dns.RcodeSuccess, fmt.Errorf("fake")).Times(1)
				})},
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			c := NewCommonContainer()
			for _, p := range test.plugin {
				err := c.Register(p.handler)
				assert.NoError(t, err)
			}
			err := c.Execute(context.TODO(), test.writer.writer, &dns.Msg{})
			assert.Equal(t, test.expectedError, err != nil)
		})
	}
}
