package service

/*
Copyright 2022 The k8gb Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"context"

	"github.com/coredns/coredns/plugin"
	"github.com/miekg/dns"
)

// PluginContainer is keeps particular services in the container and executes them
// in order they were added
type PluginContainer interface {
	Register(plugin.Handler) error
	// Execute run plugin.Handler.ServeDNS in order as it was added.
	// If error occurs, it exits immediately end return error.
	// If !dns.RcodeSuccess is returned, it exits immediately end return error.
	Execute(ctx context.Context, w dns.ResponseWriter, msg *dns.Msg) error
}
