package wrr

/*
Copyright 2022 The k8gb Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"context"
	"net"
	"testing"

	"github.com/AbsaOSS/k8s_crd/common/k8sctrl"

	"github.com/AbsaOSS/k8s_crd/common/mocks"
	"github.com/coredns/coredns/plugin/test"
	"github.com/golang/mock/gomock"
	"github.com/miekg/dns"
	"github.com/stretchr/testify/assert"
)

// TODO: combina A, AAA, MX CNAme records
// TODO: endpoint values!
type fakeWriter struct {
	w dns.ResponseWriter
}

func newFakeWriter(ctrl *gomock.Controller, f func(w *mocks.MockResponseWriter)) fakeWriter {
	w := mocks.NewMockResponseWriter(ctrl)
	f(w)
	return fakeWriter{
		w: w,
	}
}

func TestWeightRoundRobin(t *testing.T) {
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	const label = "k8gb.absa.oss/dnstype=local"
	const host = "roundrobin.cloud.example.com"

	defaultEP := k8sctrl.LocalDNSEndpoint{
		DNSName: host,
		Labels:  map[string]string{"strategy": "roundrobin"},
		Targets: []string{"10.0.0.1", "10.0.0.2"},
	}

	tests := []struct {
		name          string
		msg           *dns.Msg
		writer        fakeWriter
		expectedError bool
		rcode         int
		lookup        k8sctrl.LookupEndpoint
	}{
		{
			name:          "Serve empty answers",
			msg:           &dns.Msg{},
			writer:        newFakeWriter(ctrl, func(w *mocks.MockResponseWriter) {}),
			expectedError: false,
		},

		{
			name: "Serve empty endpoint",
			msg: &dns.Msg{
				Answer: []dns.RR{
					test.A("alpha.cloud.example.com.		300	IN	A			10.240.0.1"),
					test.A("alpha.cloud.example.com.		300	IN	A			10.240.0.2"),
					test.A("alpha.cloud.example.com.		300	IN	A			10.240.0.3"),
				},
			},
			writer:        newFakeWriter(ctrl, func(w *mocks.MockResponseWriter) {}),
			expectedError: false,
			lookup: func(indexKey string, clientIP net.IP) (result k8sctrl.LocalDNSEndpoint) {
				return defaultEP
			},
			rcode: dns.RcodeSuccess,
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			wrr := NewWeightRoundRobin()
			k8sctrl.Resources.DNSEndpoint.Lookup = test.lookup
			code, err := wrr.ServeDNS(context.TODO(), test.writer.w, test.msg)
			assert.Equal(t, test.rcode, code)
			assert.Equal(t, test.expectedError, err != nil)
		})

	}
}
