package k8sctrl

/*
Copyright 2022 The k8gb Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"context"
	"reflect"
	"sort"
	"testing"
	"unsafe"

	"github.com/k8gb-io/coredns-crd-plugin/common/mocks"
	"go.uber.org/mock/gomock"

	"sigs.k8s.io/external-dns/apis/v1alpha1"
	"sigs.k8s.io/external-dns/endpoint"

	dnsendpoint "github.com/k8gb-io/coredns-crd-plugin/extdns"
	"github.com/stretchr/testify/assert"
	"k8s.io/client-go/rest"
	"k8s.io/client-go/tools/cache"
)

func TestKubeController(t *testing.T) {
	const label = "k8gb.absa.oss/dnstype=local"
	const host = "roundrobin.cloud.example.com"
	const hOSTCaseInsensitive = "roundrobin-case-insensitive.CLOUD.EXAMPLE.COM"
	const hostCaseInsensitive = "roundrobin-case-insensitive.cloud.example.com"
	const embeddedCaseSensitive = "embedded.CLOUD.EXAMPLE.COM"
	const embeddedCaseInsensitive = "embedded.cloud.example.com"
	var clientIP = []byte{0x0A, 0x0A, 0x0A, 0x01}
	defaultEP := &v1alpha1.DNSEndpoint{
		Spec: v1alpha1.DNSEndpointSpec{
			Endpoints: []*endpoint.Endpoint{
				{
					DNSName: "localtargets-" + host,
				},
				{
					DNSName: host,
					Labels:  map[string]string{"strategy": "roundrobin"},
					Targets: []string{"10.0.0.1", "10.0.0.2"},
				},
				{
					DNSName: hOSTCaseInsensitive,
					Labels:  map[string]string{"strategy": "roundrobin"},
					Targets: []string{"1.1.1.1", "1.1.1.2"},
				},
				{
					DNSName: hostCaseInsensitive,
					Labels:  map[string]string{"strategy": "roundrobin"},
					Targets: []string{"2.2.2.2"},
				},
			},
		},
	}

	ep1 := &v1alpha1.DNSEndpoint{
		Spec: v1alpha1.DNSEndpointSpec{
			Endpoints: []*endpoint.Endpoint{
				{
					DNSName: "localtargets-" + hOSTCaseInsensitive,
				},
				{
					DNSName: hOSTCaseInsensitive,
					Labels:  map[string]string{"strategy": "roundrobin"},
					Targets: []string{"1.1.1.1", "1.1.1.2"},
				},
			},
		},
	}

	ep2 := &v1alpha1.DNSEndpoint{
		Spec: v1alpha1.DNSEndpointSpec{
			Endpoints: []*endpoint.Endpoint{
				{
					DNSName: "localtargets-" + hOSTCaseInsensitive,
				},
				{
					DNSName: hostCaseInsensitive,
					Labels:  map[string]string{"strategy": "roundrobin"},
					Targets: []string{"2.2.2.2"},
				},
			},
		},
	}

	epEmbedded := &v1alpha1.DNSEndpoint{
		Spec: v1alpha1.DNSEndpointSpec{
			Endpoints: []*endpoint.Endpoint{
				{
					DNSName: "localtargets-" + embeddedCaseSensitive,
				},
				{
					DNSName: embeddedCaseInsensitive,
					Labels:  map[string]string{"strategy": "roundrobin"},
					Targets: []string{"10.10.10.32", "10.10.10.30"},
				},
				{
					DNSName: embeddedCaseSensitive,
					Labels:  map[string]string{"strategy": "roundrobin"},
					Targets: []string{"10.10.10.2"},
				},
			},
		},
	}

	ctrl := gomock.NewController(t)
	defer ctrl.Finish()
	mctrl := mocks.NewMockInterface(ctrl)
	mcache := mocks.NewMockSharedIndexInformer(ctrl)
	midx := mocks.NewMockIndexer(ctrl)
	midx.EXPECT().List().Return([]interface{}{defaultEP, ep1, ep2, epEmbedded}).AnyTimes()
	mcache.EXPECT().GetIndexer().Return(midx).AnyTimes()

	client := getClient(mctrl)

	var k8sctrl *KubeController
	t.Run("initialize", func(t *testing.T) {
		k8sctrl = NewKubeController(context.TODO(), client, []string{label})
		assert.NotNil(t, k8sctrl)
		assert.False(t, k8sctrl.HasSynced())
		assert.Equal(t, 1, len(k8sctrl.controllers))
	})

	k8sctrl.endpointControllers = []cache.SharedIndexInformer{mcache}

	t.Run("get no-geo endpoint by name", func(t *testing.T) {
		lep := k8sctrl.getEndpointByName(host, clientIP, "")
		assert.NotNil(t, lep)
		assert.Equal(t, "roundrobin.cloud.example.com: 0, Targets: [10.0.0.1 10.0.0.2], Labels: map[strategy:roundrobin]", lep.String())
	})

	t.Run("valid uppercase domain query", func(t *testing.T) {
		lep := k8sctrl.getEndpointByName(hOSTCaseInsensitive, clientIP, "")
		assert.NotNil(t, lep)
		sort.Strings(lep.Targets)
		assert.Equal(t, "roundrobin-case-insensitive.CLOUD.EXAMPLE.COM: 0, Targets: [1.1.1.1 1.1.1.2 2.2.2.2], Labels: map[strategy:roundrobin]", lep.String())

		lep = k8sctrl.getEndpointByName(hostCaseInsensitive, clientIP, "")
		assert.NotNil(t, lep)
		sort.Strings(lep.Targets)
		assert.Equal(t, "roundrobin-case-insensitive.cloud.example.com: 0, Targets: [1.1.1.1 1.1.1.2 2.2.2.2], Labels: map[strategy:roundrobin]", lep.String())
	})

	t.Run("handle multiple embedded endpoints", func(t *testing.T) {
		lep := k8sctrl.getEndpointByName(embeddedCaseInsensitive, clientIP, "")
		assert.NotNil(t, lep)
		sort.Strings(lep.Targets)
		assert.Equal(t, "embedded.cloud.example.com: 0, Targets: [10.10.10.2 10.10.10.30 10.10.10.32], Labels: map[strategy:roundrobin]", lep.String())

		lep = k8sctrl.getEndpointByName(embeddedCaseSensitive, clientIP, "")
		assert.NotNil(t, lep)
		sort.Strings(lep.Targets)
		assert.Equal(t, "embedded.CLOUD.EXAMPLE.COM: 0, Targets: [10.10.10.2 10.10.10.30 10.10.10.32], Labels: map[strategy:roundrobin]", lep.String())
	})

	t.Run("handle multiple embedded endpoints but one EP is empty", func(t *testing.T) {
		epEmbedded.Spec.Endpoints[1].Targets = []string{}
		lep := k8sctrl.getEndpointByName(embeddedCaseInsensitive, clientIP, "")
		assert.NotNil(t, lep)
		assert.Equal(t, "embedded.cloud.example.com: 0, Targets: [10.10.10.2], Labels: map[strategy:roundrobin]", lep.String())

		lep = k8sctrl.getEndpointByName(embeddedCaseSensitive, clientIP, "")
		assert.NotNil(t, lep)
		assert.Equal(t, "embedded.CLOUD.EXAMPLE.COM: 0, Targets: [10.10.10.2], Labels: map[strategy:roundrobin]", lep.String())

	})

	t.Run("EP has empty targets", func(t *testing.T) {
		epEmbedded.Spec.Endpoints[1].Targets = []string{}
		epEmbedded.Spec.Endpoints[2].Targets = []string{}
		epEmbedded.Spec.Endpoints[0].Targets = []string{}
		lep := k8sctrl.getEndpointByName(embeddedCaseInsensitive, clientIP, "")
		assert.NotNil(t, lep)
		assert.Equal(t, "embedded.cloud.example.com: 0, Targets: [], Labels: map[strategy:roundrobin]", lep.String())

		lep = k8sctrl.getEndpointByName(embeddedCaseSensitive, clientIP, "")
		assert.NotNil(t, lep)
		assert.Equal(t, "embedded.CLOUD.EXAMPLE.COM: 0, Targets: [], Labels: map[strategy:roundrobin]", lep.String())
	})

	t.Run("EP has no dns endpoints", func(t *testing.T) {
		epEmbedded.Spec.Endpoints = []*endpoint.Endpoint{}
		lep := k8sctrl.getEndpointByName(embeddedCaseInsensitive, clientIP, "")
		assert.NotNil(t, lep)
		assert.Equal(t, "embedded.cloud.example.com: 0, Targets: [], Labels: map[]", lep.String())

		lep = k8sctrl.getEndpointByName(embeddedCaseSensitive, clientIP, "")
		assert.NotNil(t, lep)
		assert.Equal(t, "embedded.CLOUD.EXAMPLE.COM: 0, Targets: [], Labels: map[]", lep.String())
	})

	t.Run("EP has nil dns endpoints", func(t *testing.T) {
		epEmbedded.Spec.Endpoints = nil
		lep := k8sctrl.getEndpointByName(embeddedCaseInsensitive, clientIP, "")
		assert.NotNil(t, lep)
		assert.Equal(t, "embedded.cloud.example.com: 0, Targets: [], Labels: map[]", lep.String())

		lep = k8sctrl.getEndpointByName(embeddedCaseSensitive, clientIP, "")
		assert.NotNil(t, lep)
		assert.Equal(t, "embedded.CLOUD.EXAMPLE.COM: 0, Targets: [], Labels: map[]", lep.String())
	})

}

func getClient(i rest.Interface) (c *dnsendpoint.ExtDNSClient) {
	c = &dnsendpoint.ExtDNSClient{}
	rs := reflect.ValueOf(c)
	q := (*rest.Interface)(unsafe.Pointer(rs.Elem().FieldByName("restClient").UnsafeAddr()))
	*q = i
	return c
}

func TestMatchesWildcard(t *testing.T) {
	tests := []struct {
		name     string
		pattern  string
		hostname string
		expected bool
	}{
		{
			name:     "exact wildcard match",
			pattern:  "*.example.com",
			hostname: "test.example.com",
			expected: true,
		},
		{
			name:     "wildcard match case insensitive",
			pattern:  "*.example.com",
			hostname: "TEST.EXAMPLE.COM",
			expected: true,
		},
		{
			name:     "wildcard should not match apex domain",
			pattern:  "*.example.com",
			hostname: "example.com",
			expected: false,
		},
		{
			name:     "wildcard should not match subdomain",
			pattern:  "*.example.com",
			hostname: "sub.test.example.com",
			expected: false,
		},
		{
			name:     "wildcard should not match different domain",
			pattern:  "*.example.com",
			hostname: "test.example.org",
			expected: false,
		},
		{
			name:     "non-wildcard pattern should not match",
			pattern:  "test.example.com",
			hostname: "test.example.com",
			expected: false,
		},
		{
			name:     "wildcard with multiple labels",
			pattern:  "*.cloud.example.com",
			hostname: "app.cloud.example.com",
			expected: true,
		},
		{
			name:     "wildcard with multiple labels should not match deeper subdomain",
			pattern:  "*.cloud.example.com",
			hostname: "sub.app.cloud.example.com",
			expected: false,
		},
		{
			name:     "wildcard should not match partial suffix",
			pattern:  "*.example.com",
			hostname: "testexample.com",
			expected: false,
		},
		{
			name:     "empty hostname should not match",
			pattern:  "*.example.com",
			hostname: "",
			expected: false,
		},
		{
			name:     "wildcard with dashes",
			pattern:  "*.example-site.com",
			hostname: "app-test.example-site.com",
			expected: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := matchesWildcard(tt.pattern, tt.hostname)
			assert.Equal(t, tt.expected, result, "matchesWildcard(%q, %q) = %v, want %v", tt.pattern, tt.hostname, result, tt.expected)
		})
	}
}

func TestWildcardDNSEndpoint(t *testing.T) {
	const label = "k8gb.absa.oss/dnstype=local"
	var clientIP = []byte{0x0A, 0x0A, 0x0A, 0x01}

	t.Run("wildcard match", func(t *testing.T) {
		wildcardEP := &v1alpha1.DNSEndpoint{
			Spec: v1alpha1.DNSEndpointSpec{
				Endpoints: []*endpoint.Endpoint{
					{
						DNSName: "*.example.com",
						Targets: []string{"192.168.1.1", "192.168.1.2"},
						Labels:  map[string]string{"strategy": "roundrobin"},
					},
				},
			},
		}

		ctrl := gomock.NewController(t)
		defer ctrl.Finish()
		mctrl := mocks.NewMockInterface(ctrl)
		mcache := mocks.NewMockSharedIndexInformer(ctrl)
		midx := mocks.NewMockIndexer(ctrl)

		midx.EXPECT().List().Return([]interface{}{wildcardEP}).AnyTimes()
		mcache.EXPECT().GetIndexer().Return(midx).AnyTimes()

		client := getClient(mctrl)
		k8sctrl := NewKubeController(context.TODO(), client, []string{label})
		k8sctrl.endpointControllers = []cache.SharedIndexInformer{mcache}

		// Query for a subdomain that should match the wildcard
		lep := k8sctrl.getEndpointByName("test.example.com", clientIP, "")
		assert.NotNil(t, lep)
		assert.Equal(t, 2, len(lep.Targets))
		assert.Contains(t, lep.Targets, "192.168.1.1")
		assert.Contains(t, lep.Targets, "192.168.1.2")
	})

	t.Run("wildcard should not match apex domain", func(t *testing.T) {
		wildcardEP := &v1alpha1.DNSEndpoint{
			Spec: v1alpha1.DNSEndpointSpec{
				Endpoints: []*endpoint.Endpoint{
					{
						DNSName: "*.example.com",
						Targets: []string{"192.168.1.1", "192.168.1.2"},
						Labels:  map[string]string{"strategy": "roundrobin"},
					},
				},
			},
		}

		ctrl := gomock.NewController(t)
		defer ctrl.Finish()
		mctrl := mocks.NewMockInterface(ctrl)
		mcache := mocks.NewMockSharedIndexInformer(ctrl)
		midx := mocks.NewMockIndexer(ctrl)

		midx.EXPECT().List().Return([]interface{}{wildcardEP}).AnyTimes()
		mcache.EXPECT().GetIndexer().Return(midx).AnyTimes()

		client := getClient(mctrl)
		k8sctrl := NewKubeController(context.TODO(), client, []string{label})
		k8sctrl.endpointControllers = []cache.SharedIndexInformer{mcache}

		// Query for apex domain should not match wildcard
		lep := k8sctrl.getEndpointByName("example.com", clientIP, "")
		assert.NotNil(t, lep)
		assert.Equal(t, 0, len(lep.Targets))
	})

	t.Run("exact match takes precedence over wildcard", func(t *testing.T) {
		wildcardEP := &v1alpha1.DNSEndpoint{
			Spec: v1alpha1.DNSEndpointSpec{
				Endpoints: []*endpoint.Endpoint{
					{
						DNSName: "*.example.com",
						Targets: []string{"192.168.1.1", "192.168.1.2"},
						Labels:  map[string]string{"strategy": "roundrobin"},
					},
				},
			},
		}

		exactMatchEP := &v1alpha1.DNSEndpoint{
			Spec: v1alpha1.DNSEndpointSpec{
				Endpoints: []*endpoint.Endpoint{
					{
						DNSName: "specific.example.com",
						Targets: []string{"10.0.0.1"},
						Labels:  map[string]string{},
					},
				},
			},
		}

		ctrl := gomock.NewController(t)
		defer ctrl.Finish()
		mctrl := mocks.NewMockInterface(ctrl)
		mcache := mocks.NewMockSharedIndexInformer(ctrl)
		midx := mocks.NewMockIndexer(ctrl)

		midx.EXPECT().List().Return([]interface{}{wildcardEP, exactMatchEP}).AnyTimes()
		mcache.EXPECT().GetIndexer().Return(midx).AnyTimes()

		client := getClient(mctrl)
		k8sctrl := NewKubeController(context.TODO(), client, []string{label})
		k8sctrl.endpointControllers = []cache.SharedIndexInformer{mcache}

		// Query for specific.example.com should return exact match, not wildcard
		lep := k8sctrl.getEndpointByName("specific.example.com", clientIP, "")
		assert.NotNil(t, lep)
		assert.Equal(t, 1, len(lep.Targets), "Expected 1 target, got %d: %v", len(lep.Targets), lep.Targets)
		assert.Contains(t, lep.Targets, "10.0.0.1")
		assert.NotContains(t, lep.Targets, "192.168.1.1")
	})
}
