package k8sctrl

/*
Copyright 2022 The k8gb Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"context"
	"reflect"
	"testing"
	"unsafe"

	"github.com/AbsaOSS/k8s_crd/common/mocks"

	"sigs.k8s.io/external-dns/endpoint"

	dnsendpoint "github.com/AbsaOSS/k8s_crd/extdns"
	"github.com/golang/mock/gomock"
	"github.com/stretchr/testify/assert"
	"k8s.io/client-go/rest"
)

func TestKubeController(t *testing.T) {
	const label = "k8gb.absa.oss/dnstype=local"
	const host = "roundrobin.cloud.example.com"
	defaultEP := &endpoint.DNSEndpoint{
		Spec: endpoint.DNSEndpointSpec{
			Endpoints: []*endpoint.Endpoint{
				{
					DNSName: "localtargets-" + host,
				},
				{
					DNSName: host,
					Labels:  map[string]string{"strategy": "roundrobin"},
					Targets: []string{"10.0.0.1", "10.0.0.2"},
				},
			},
		},
	}
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()
	mctrl := mocks.NewMockInterface(ctrl)
	mcache := mocks.NewMockSharedIndexInformer(ctrl)
	midx := mocks.NewMockIndexer(ctrl)
	midx.EXPECT().ByIndex(endpointHostnameIndex, host).Return([]interface{}{defaultEP}, nil).Times(1)
	mcache.EXPECT().GetIndexer().Return(midx)

	client := getClient(mctrl)

	var k8sctrl *KubeController
	t.Run("initialize", func(t *testing.T) {
		k8sctrl = NewKubeController(context.TODO(), client, label)
		assert.NotNil(t, k8sctrl)
		assert.False(t, k8sctrl.HasSynced())
		assert.Equal(t, 1, len(k8sctrl.controllers))
	})

	k8sctrl.epc = mcache

	t.Run("get no-geo endpoint by name", func(t *testing.T) {
		lep := k8sctrl.getEndpointByName("roundrobin.cloud.example.com", []byte{0x0A, 0x0A, 0x0A, 0x01})
		assert.NotNil(t, lep)
		assert.Equal(t, "roundrobin.cloud.example.com: 0, Targets: [10.0.0.1 10.0.0.2], Labels: map[strategy:roundrobin]", lep.String())
	})

}

func getClient(i rest.Interface) (c *dnsendpoint.ExtDNSClient) {
	c = &dnsendpoint.ExtDNSClient{}
	rs := reflect.ValueOf(c)
	q := (*rest.Interface)(unsafe.Pointer(rs.Elem().FieldByName("restClient").UnsafeAddr()))
	*q = i
	return c
}
